
jupyterlab:
  build: ./jupyterlab
  ports:
    - "8888:8888"
  volumes:
    - ./:/opt/app/data
  entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root'
